### ISSUE TITLE
Add website to rom view page

### ISSUE THREAD

**Issue by g7755725** [romhut/romhut.com#16]
Can you readd back website url to our main website tge forum link is fine but also having our personal site is better too and is it possible creating a actual romhut android app or no so we can upload our roms from it too and last one and where can i find dev dashboard i dont see it in the nav anymore i have to type it manually?

**Comment by scottrobertson** [comment]
I shall get the website link added to the rom page. 

There won't be a romhut app in the near future sadly.

**Comment by g7755725** [comment]
Oh ok
