### ISSUE TITLE
Users reporting downloading devs.bin (no rom.zip)

### ISSUE THREAD

**Issue by Joshndroid** [romhut/romhut.com#18]
Hello,

Users of my roms are reporting issues with the rom file being downloaded as a devs.bin. I originally figured it may be an issue with naming to which i advised to change to a devs.zip however this does not fix the problem. It has happened on and off over the last couple of months and just thought i should probably at least raise it in case your not aware of any issue.

Sample of user's post regarding issue - http://forum.xda-developers.com/showpost.php?p=61656016&postcount=1076

Thanks,

Joshndroid

**Comment by scottrobertson** [comment]
Thank @Joshndroid.

I have sorted it for this 1 download.

What is the file name when you uploaded it? It uses the filename that you specify. I am not sure why it would strip the .zip off the end. There is no code to do that.

**Comment by Joshndroid** [comment]
i had it named cm-12.1-20150701-UNOFFICIAL-temasek-lt03wifi-v14.3.zip when uploading. Then manually removed the .zip ONLY in the name, as users reported that on download it would create .zip.zip

it has happened a few times over the last few months, unsure of what it may be?
