### ISSUE TITLE
Upload Error

### ISSUE THREAD

**Issue by g7755725** [romhut/romhut.com#2]
I getting a something went wrong message after uploading via dropbox and plublishing it and it doesnt show upload complete anymore to see if it uploaded sucessfully.

**Comment by scottrobertson** [comment]
Just done a huge deployment, you may have just had bad timing. Give me 10 minutes and I will get back to you.

**Comment by scottrobertson** [comment]
Ok, this should be sorted. Let me know if you find anything else. This deployment was pretty big, but it allows us to do some awesome stuff going forward. More to come!

**Comment by g7755725** [comment]
Yes it works now

**Comment by scottrobertson** [comment]
Awesome, let me know if you have any other issues, or if you have any feature requests.
