### ISSUE TITLE
ROMHut failing to upload and show rom to reentry again

### ISSUE THREAD

**Issue by g7755725** [romhut/romhut.com#20]
The site is failing to upload my rom and it doesmt even show it's there when i reupload  again says i put a version that doesnt even exists in tge versions page can you fix asap!

**Comment by scottrobertson** [comment]
Host seems to be having a few issues at the moment.

**Comment by g7755725** [comment]
Will i be able to reupload the same version again  after its fixed instead if changing the rom version in buiod prop and waste my bandwidth?

**Comment by scottrobertson** [comment]
Can you send me the link to your rom, and i will take a look when i get some time

**Comment by g7755725** [comment]
I uploaded it via dropbox tge version it was is 20150726 https://www.dropbox.com/s/jxlweq598abnnbe/GR8_v2.5_For_jfltetmo.zip?dl=1 and heres were i upload it to https://romhut.com/roms/gamerrom-8 for users to get the update

**Comment by g7755725** [comment]
But seems to not show up on tge site when to publish it and begore kept saying downloading but nothing

**Comment by scottrobertson** [comment]
Yeah, the workers are having a few issues connecting to the DB at the moment.

**Comment by g7755725** [comment]
Alright so wen they fix i can retry it And wont get that problem again sayingnthe same version is uploaded?

**Comment by scottrobertson** [comment]
I will have to remove the pending version manually

**Comment by scottrobertson** [comment]
However, it should process this one

**Comment by g7755725** [comment]
Thanks wen u delete it can you close this so ill know its ready and i can reupload it?

**Comment by scottrobertson** [comment]
Sure. I probably wont delete it though, as it should complete when the jobs are able to run.

**Comment by scottrobertson** [comment]
There you go, it seems to have complete. Moving the site to a new DB at the moment, so there may be a little bit of downtime

**Comment by g7755725** [comment]
Great i noticed and thanks
