### ISSUE TITLE
Dev account

### ISSUE THREAD

**Issue by arny24x7** [romhut/romhut.com#25]
Why are u not giving me access to dev account ???

**Comment by scottrobertson** [comment]
There is a huge backlog. We are working through them.

**Comment by arny24x7** [comment]
i had applied 3 months before..then deleted and I was forced to move to otaupdatecenter.pro...i re-applied..and now this never mind.

**Comment by scottrobertson** [comment]
Romhut is a side project, i have a full time job, and other side projects. Time is limited.

**Comment by arny24x7** [comment]
Thanx man..il move on to some other service as i have to provide ota regularly for multiple roms.
