### ISSUE TITLE
No pushbullet button

### ISSUE THREAD

**Issue by ghost** [romhut/romhut.com#27]
![no pushbullet](https://cloud.githubusercontent.com/assets/9745208/9836165/38c86468-5a0f-11e5-9d3e-c12e23ed9b60.PNG)

There is supposed to be a pushbullet button but there isn't.

**Comment by scottrobertson** [comment]
Pushbullet have messed their JS file up. Shall contact them.

**Comment by scottrobertson** [comment]
They have said they are going to fix this, but it's not done yet.

**Comment by scottrobertson** [comment]
Sorted
