### ISSUE TITLE
Updating addons

### ISSUE THREAD

**Issue by MatthewBooth** [romhut/romhut.com#3]
Addons need to be able to be updated rather than deleted and reuploaded. Currently, you have to delete an addon to reupload it. 

This also generates a new slug for that addon too, which isn't like the original.

Makes more sense to be able to edit an addon and "update" it with a new file, This should also update the addons.xml/.json to update the "updated on" time

**Comment by scottrobertson** [comment]
We need to to think about pushbullet users too. Need to look into if they would be notified or not, since they will already have had a push for that URL.
