### ISSUE TITLE
Impossible to take a version that was previously added

### ISSUE THREAD

**Issue by MatthewBooth** [romhut/romhut.com#32]
For instance if you add 20151010, then realise it is missing things or has an error in the zip, you naturally delete. However, upon uploading the correct version, you can no longer take 20151010 as your version and must increment, despite there being no such version for your ROM (as you deleted it)

**Comment by scottrobertson** [comment]
Is this something we want? If people download the old upload and you delete it and upload a new rom with the same version, people won't know to upgrade. Why not just increment?

**Comment by MatthewBooth** [comment]
That ROMs zip now says 2151101 in the ota but 20151101 on the site :(

Maybe a 15-30 time limit on changes or something?

**Comment by scottrobertson** [comment]
But why are you uploading the same rom twice? Confused.

**Comment by scottrobertson** [comment]
Version numbers are supposed to be unique, it's not really a romhut specific thing?

**Comment by MatthewBooth** [comment]
Because the version uploaded had an error? So it had to be replaced but was the same day

**Comment by scottrobertson** [comment]
Was it released?

**Comment by MatthewBooth** [comment]
Possibly. @AntaresOne will know!

**Comment by scottrobertson** [comment]
If so, then it should be incremented, that is just how version numbers should work. This is a limitation of using dates as version numbers.
