### ISSUE TITLE
Need version marshmallow 6.0.1 added please

### ISSUE THREAD

**Issue by Joshndroid** [romhut/romhut.com#36]
Hello, 
We now require the version of 6.0.1 added to the list. 
Almost every release I have people asking why it is still 6.0.0. I have to tell them everytime that it is 6.0.1. Can you please add the newer version listing so I can select it from the drop down on version creation?
Thanks
Joshndroid

**Comment by scottrobertson** [comment]
Added :)

**Comment by Joshndroid** [comment]
Thanks mate
