### ISSUE TITLE
New version still pending so long (about 15 h.)

### ISSUE THREAD

**Issue by GeorgiiFirsov** [romhut/romhut.com#38]
I uploaded the new version of my rom 15 hours ago, but it still pending now.

**Comment by AntaresOne** [comment]
Same here, tried to upload multiple times with both web and remote uploaders

**Comment by scottrobertson** [comment]
Sorry about that. Shall have a look as soon as I can.

**Comment by AntaresOne** [comment]
@scottrobertson no problem mate, after all it's a free service so we shouldn't complain. I checked my latest upload some hours ago and finally "Pending" is gone. :)

**Comment by GeorgiiFirsov** [comment]
@scottrobertson Now site works fine. Thanks. I think that it was overload of server. But maybe it was bug.
Anyway big thanks for ROMHUT!!!
