### ISSUE TITLE
Login authorities

### ISSUE THREAD

**Issue by MatthewBooth** [romhut/romhut.com#4]
- [x] Github
- [ ] Bitbucket
- [ ] OpenID
- [ ] Microsoft
- [x] Twitter

[OmniAuth](https://github.com/intridea/omniauth)

**Comment by scottrobertson** [comment]
Bitbucket one is shit, doesn't work. 
OpenID is going to be annoying, and no one will use it anyway
And shall do the microsoft one sometime soon (it's a bit faffy).

**Comment by MatthewBooth** [comment]
"Scott: Make a list of them on GitHub"

_makes list_

"Scott: They're all crap"

**Comment by scottrobertson** [comment]
To be fair, I did say I wasnt going to do openid. And I did attempt the other 2, but Bitbucket is just awful and just shows some shitty page with no CSS or actions, and Microsoft is Microsoft.
