### ISSUE TITLE
New upload completed but shown as "Pending"

### ISSUE THREAD

**Issue by smeroni68** [romhut/romhut.com#40]
Tryed several times to upload a new rom version, from Dropbox aswell from local, upload complete, but is not possible to publish because status is "Pending"... Huston we have a problem!

**Comment by Joshndroid** [comment]
I further confirm this error the past few days. No local or remote URL is allowing for it to upload

**Comment by scottrobertson** [comment]
@smeroni68 @Joshndroid sorry for the slow response, been in disneyland.

So, the docker containers seem to have crashed, and for some reason Dokku didn't bring them back online. It's happened a couple of times now when I don't deploy in quite a while. I will look into it and file a bug report with them. Shall redeploy every few days now automatically to try and stop it for now.

**Comment by smeroni68** [comment]
No problem @scottrobertson ... thanks for your time!

**Comment by smeroni68** [comment]
@scottrobertson: still blocked now... Upload completed and PENDING...

EDIT: Is becoming hard to survive with this malfunctioning...

**Comment by Joshndroid** [comment]
I am also having the pending error. I can add the URL location however it just stays on pending, with file not uploading/becoming available

**Comment by scottrobertson** [comment]
Upgraded dokku to the lastest version, seeing if that helps.

**Comment by scottrobertson** [comment]
Sorry about this. Super annoying for me too.

**Comment by smeroni68** [comment]
Important for you and for us is to try to find a solution... thanks for your time.

**Comment by Joshndroid** [comment]
finally back working as of yesterday for me scott, thanks

**Comment by B--B** [comment]
Hi there! @scottrobertson unfortunately i think that this issue happened again... I' ve tried to update our LP rom and kernel addon, both are stuck in pending state, tried standard/remote/dp upload and still the same problem..!

**Comment by scottrobertson** [comment]
I have restarted the docker instances for the workers. I have reported this issue to Dokku, but they cannot find the issue just yet.

**Comment by B--B** [comment]
I can confirm it's working now, i've published the addon and downloaded without any issue! Thanks Scott! :-)

**Comment by B--B** [comment]
@scottrobertson happened again now, tried to upload from db, stuck as "pending" after 15 minutes..!

**Comment by scottrobertson** [comment]
I have just moved the site away from Dokku. Hopefully this helps with the issue

**Comment by B--B** [comment]
Now works again, thanks Scott!

**Comment by B--B** [comment]
@scottroberson still the same issue again, upload from Dropbox stucks in pending state, tried now and it's not working again..

**Comment by scottrobertson** [comment]
Sick of this.... shall look into it when I can.

**Comment by B--B** [comment]
No worries Scoot, take your time!
