### ISSUE TITLE
No mms on  Optimized CM 13  

### ISSUE THREAD

**Issue by marctravers77** [romhut/romhut.com#44]
Mms will not work... I've tried various messengers  with no luck.   The isn't a way to check APN IN THE OS  like in CM12 version.    The version I'm having this issue in is Optimized  CM13  build 03.29.  I went back to  Optimized  12  January build..  And MMS works fine.  I'm running on a USC SCH-R970

**Comment by scottrobertson** [comment]
This repository is for romhut.com issues only. Please submit any ROM issues directly to the developers.
