### ISSUE TITLE
Canceled: ROMHUT still charging me!

### ISSUE THREAD

**Issue by ken48228** [romhut/romhut.com#45]
I canceled my Romhut Pro account.

They are still charging me!!

Tried calling, phone number is invalid!!

Tried e-mailing. No response!!

**Comment by scottrobertson** [comment]
I will look into this now for you. Can i just ask, what phone number are you calling? We don't have a published phone number anywhere.

**Comment by scottrobertson** [comment]
I have cancelled your subscription and refunded your email. 

It looks like there was an issue with our email provider. They were not collecting the emails sent to our support address for some reason.

**Comment by ken48228** [comment]
Thank you,
The phone number is at the bottom of the e-mail confirming the charge.Also the email showing the refund. 
| 
| 
| 
| You received a refund of $1.99. |

 |

|   |
| 
|  | 
|  |
|   |
| Romhut started a refund of$1.99 |
|   |
| 
|   |

 |
|   |
| 
|  |   | 3767 |

 |

 |  |

 |
|   |

|
|
|
|

 |

 |

|
|
|
|

 |

|
|
|
|
|
|
|
|
|
|
|
|
|
|
|
|
|
|

 |

 |  |

 |

|
|
|
|
|
|

 |

 |

|
|
|
|
|
|

 |

 |

Sent from Yahoo Mail on Android 

  On Sun, May 1, 2016 at 6:07 PM, Scott Robertsonnotifications@github.com wrote:  
I will look into this now for you. Can i just ask, what phone number are you calling? We don't have a published phone number anywhere.

**Comment by scottrobertson** [comment]
It looks like Stripe has messed up the UK phone number formatting. Shall have a look into it.

**Comment by ken48228** [comment]
Scott fixed the issue and refunded the charge.

Thank you.
