### ISSUE TITLE
ROM Version list... Update for Nougat 7.0.0

### ISSUE THREAD

**Issue by smeroni68** [romhut/romhut.com#53]
Hi Scott, we are releasing Nougat 7.0.0 AOSP rom for JFLTE devices and in the version list is not available Nougat 7.0.0

Is it possible to add it in the choice list?

Thanks for your help.

**Comment by scottrobertson** [comment]
Added. Sorry for the delay :)

**Comment by smeroni68** [comment]
No problem. Thanks.
