### ISSUE TITLE
Links are not working

### ISSUE THREAD

**Issue by zabihchaudhry** [romhut/romhut.com#54]
Download links are not working since two days....
https://romhut.com/versions/aosp-6-0-20160909-jflte-zip
![screenshot_20161010-101243](https://cloud.githubusercontent.com/assets/20650525/19226388/535161fa-8ef6-11e6-9f68-36e7610f044e.png)

**Comment by scottrobertson** [comment]
Looks like the NYC server is down. Will look into it asap.

**Comment by scottrobertson** [comment]
All sorted.
