### ISSUE TITLE
Romhut pri

### ISSUE THREAD

**Issue by elv1503** [romhut/romhut.com#56]
Romhut have been taking a subscription from me for the last two months for Romhut Pro. I don't have access to Romhut Pro. I have emailed Romhut support to cancel subscription  but I have not received a reply. I am now requesting that my subscription be cancelled and that I receive a refund.

**Comment by elv1503** [comment]
Further to earlier post, each time I use Romhut I get a request to subscripe to Romhut Pro.

**Comment by scottrobertson** [comment]
@elv1503 can you email again, does not seem to be in our mailbox for some reason.
