### ISSUE TITLE
Working OTAUpdates Version

### ISSUE THREAD

**Issue by B--B** [romhut/romhut.com#60]
Hi Scott, just realised that official OTAUpdates apk does not work at all on MM/Nougat ROMs, some people contacted me in PVT asking me how our version is working so i decided to open this report :)
Our OTAUpdates works pretty fine (big big thanks to @antaresone that updated the app for N) so if you guys wants to temporary use it until official apk is updated feel absolutely free to use it! 

Here's the apk link: https://www.dropbox.com/s/itjkj1cpu88cesx/OTAUpdates.apk?dl=0
And here's the sources repo used for compiling: https://github.com/AOSP-JF-MM/platform_packages_apps_OTAUpdates/tree/RomHut

Tested on my ROM (JF variant) ,copy/paste the apk on /system/app and works fine :)

Hope it helps

**Comment by scottrobertson** [comment]
Hey. I don't actually make any of that side of things. I will let Matt take it from here.

**Comment by B--B** [comment]
Ok, thanks Scott :)
