### ISSUE TITLE
Canceling Pro Account

### ISSUE THREAD

**Issue by Mrozeko** [romhut/romhut.com#61]
Hello,

I want to cancel the Pro Account But there is no Option to do this on the Page. I wrote emails But still didnt get response.

Please deactivate My Pro Account and stop charging My debit card. Otherwise i have to inform My credit card company and block all future transactions.

**Comment by Mrozeko** [comment]
My Account Mail is ---------

**Comment by scottrobertson** [comment]
Did you try cancelling it at romhut.com/pro?

**Comment by Mrozeko** [comment]
Hello Scott, TY for repley

Yes i did...
After i logged in - the Page " romhut.com/pro? "
shoes no Information about the pro account.

The offter me a Pro Account and i see the comparsion of monthly and yearly pay...
But still charging me :/ 

Please Cancel this

**Comment by scottrobertson** [comment]
What does the page show?

**Comment by scottrobertson** [comment]
Please try the page again, you should be able to cancel now. Sorry about that.

**Comment by Mrozeko** [comment]
it works...Thank you

**Comment by Mrozeko** [comment]
will i get a refund ?

**Comment by scottrobertson** [comment]
@Mrozeko you will :) it's been processed by stripe now.
