### ISSUE TITLE
IMPOSSIBLE to upload anything...

### ISSUE THREAD

**Issue by smeroni68** [romhut/romhut.com#64]
Hi Scott, is from long time that is nearly impossible to upload any file into our roms socket.
I already send some messages through the web interface to advise... but had no answer...

The problem is the failing of any upload, rom from Dropbox and from local upload, addon kernels and files... the site has become completely unusable.
If is a maintenance problem, we can understand, but seems that romhut has been "abandoned" and no one is using it anymore... is that true? Sorry for the question, but if the service is unusable, would be good to know from you directly, and unluckyly we will search an alternative and move away.

The clear answer we would like to have is: romhut still alive/maintained or not? To us seems not.

Thanks for your cooperation.

**Comment by scottrobertson** [comment]
It's still active yeah. It's just that no one has reported any issues...

Can you give me some more info on the issue, potentially some screenshots of the chrome developer console too when it errors out.

**Comment by scottrobertson** [comment]
I just fixed a bug, can you try again?

We migrated to Digital Ocean Spaces a few weeks ago, which required quite a huge amount of changes, so it's probably just related to that.

**Comment by smeroni68** [comment]
Hi Scott,
the first problem I see in the interface is in the **Developer Disk Usage** where is **0% (0 Bytes / 30 GB)**:

https://www.dropbox.com/s/9kytn05sgq71j1h/Screenshot%202017-12-24%2007.56.47.png?dl=0

Right now I try to click add a version and remote upload or the standard upload do nothing.

Here a previous screen of the result with failed upload:

https://www.dropbox.com/s/d67yj1411vm3w0g/Screenshot%202017-12-10%2022.11.25.png?dl=0

Please, if you need other info or test, let me know.
We where obliged to share our roms over afh without ota support...

Thanks a lot.

**Comment by scottrobertson** [comment]
The second issue is solved, and I am not sure what you mean by the first
issue. If it does nothing then there is no way you could see the second
issue? Have you tried again?

On 24 Dec 2017 07:06, "Stefano Meroni" <notifications@github.com> wrote:

Hi Scott,
the first problem I see in the interface is in the *Developer Disk Usage*
where is *0% (0 Bytes / 30 GB)*:

https://www.dropbox.com/s/9kytn05sgq71j1h/Screenshot%
202017-12-24%2007.56.47.png?dl=0

Right now I try to click add a version and remote upload or the standard
upload do nothing.

Here a previous screen of the result with failed upload:

https://www.dropbox.com/s/d67yj1411vm3w0g/Screenshot%
202017-12-10%2022.11.25.png?dl=0

Please, if you need other info or test, let me know.
We where obliged to share our roms over afh without ota support...

Thanks a lot.

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/romhut/romhut.com/issues/64#issuecomment-353769129>,
or mute
the thread

**Comment by smeroni68** [comment]
Yes I try many times, but the two buttons of STANDARD and REMOTE upload do nothing... I can't select the file to be uploaded... yesterday at least the normal working of the UI was correct... seems that after your bug fix the UI isn't responding as it should.

The button action that I see is this one for both STANDARD and REMOTE buttons:

https://romhut.com/dashboard/roms/aosp-jf-oreo/versions/new#

**Comment by scottrobertson** [comment]
I changed nothing about the UI yesterday at all.

Can you get me a screenshot of the browsers developer console to show javascript errors

**Comment by smeroni68** [comment]
Explain me how to... I'm using Chrome browser...

**Comment by scottrobertson** [comment]
> Ctrl+Shift+J (Windows / Linux) or Cmd+Opt+J (Mac).

**Comment by smeroni68** [comment]
![image](https://user-images.githubusercontent.com/2249303/34325637-ac3860ba-e897-11e7-8125-1a5728193409.png)

**Comment by smeroni68** [comment]
I also restart the pc... but nothing happens on buttons click action.

**Comment by scottrobertson** [comment]
Ok thanks. I will take a look when i get some time.

**Comment by smeroni68** [comment]
OK... thanks.

**Comment by smeroni68** [comment]
As I told you, the two buttons link the same page where I'm... so no redirection to local file window selection nor the page where to click dropbox button.

**Comment by scottrobertson** [comment]
Yeah there is probably just a javascript error somewhere for some reason.

**Comment by scottrobertson** [comment]
@smeroni68 try now

**Comment by scottrobertson** [comment]
@smeroni68 also, if you give me the link to the rom that says "failed", i can fix that potentially without you having to reupload it.

**Comment by smeroni68** [comment]
OK. Now I can select dropbox file... trying to upload right now... will update on result...

**Comment by smeroni68** [comment]
Fantastic... is has been uploaded as COMPLETE!!!

**Comment by smeroni68** [comment]
Seems fine... and fast too... will publish and check all is fine...
In the mean time, this rom is Oreo 8.1.0... is it possible to add the version on selection? Thanks mate!!

**Comment by smeroni68** [comment]
I just removed because I upload on wrong device!! ;)... re-uploading on right place... sorry...

EDIT: all went fine... now is published on the right place...

Thanks Scott for your prompt support... I hope now is stable romhut... really appreciated...

**Comment by scottrobertson** [comment]
Woop! Let me know if you have any other issues. 

Will get the support email fixed too.
