### ISSUE TITLE
New layout...

### ISSUE THREAD

**Issue by smeroni68** [romhut/romhut.com#65]
Hi Scott,
merry xmas first of all.
May I ask what's the meaning of the new layout I saw this morning?

YESTERDAY: 
![image](https://user-images.githubusercontent.com/2249303/34333848-25c80bf2-e941-11e7-8d9a-394bed9f726b.png)

TODAY:
![image](https://user-images.githubusercontent.com/2249303/34333860-3d2d9f14-e941-11e7-9d30-1deece3f54f5.png)

Did you see what I mean?
1- Name of the file/rom is completely cutted and unreadable (column is too small)
2- Status of the file? Is it online or offline (public or unpublic)? This is quite important and with a green/red field is very easy to see the status)
3- Dates of Publish and Upload are so big, doubled infos and less important than point 2.

Is it possible to better resize the column width and having at least all the informations as before?

SAME IN ADDON SECTION:
![image](https://user-images.githubusercontent.com/2249303/34334369-44136ca0-e946-11e7-907e-e96572d53b8e.png)

Thanks for your support.

**Comment by smeroni68** [comment]
Just some hints if you accept (to clean a bit the user experience):
- instead of the string "about 19 hours ago" or "30 days ago" using the standard date format "YYYY/MM/DD" for all info dates? This will compact the two columns.
- Background color green/red on "Published" to highlight the status?

**Comment by scottrobertson** [comment]
Hey @smeroni68 

They will be back to normal soonish. I am having to remove https://github.com/bobbytables/table_cloth and it's a bit of a nightmare.

**Comment by smeroni68** [comment]
OK... take it easy... Thanks!!

**Comment by scottrobertson** [comment]
@smeroni68 take a look now. I will be redoing the whole dashboard at some point soon any way.

**Comment by smeroni68** [comment]
All information are back... not bad mate! Thanks for your time on Xmas!
