### ISSUE TITLE
Site is fully down...

### ISSUE THREAD

**Issue by smeroni68** [romhut/romhut.com#67]
Hi Scott,
is this issue related to an update of the dashboard as you anticipated time ago?

Thanks for your reply.

**Comment by scottrobertson** [comment]
Looks like something messed up with digital oceans load balancers. Will
look when home. No idea what site it's pointing to now... How fun

**Comment by smeroni68** [comment]
Yeah... it's a strange site... thanks mate...

**Comment by scottrobertson** [comment]
All back now. You may need to clear cache

**Comment by smeroni68** [comment]
Thanks for your prompt reaction!!
