### ISSUE TITLE
Set published_at date on Addons and Version when publishing

### ISSUE THREAD

**Issue by vashin1** [romhut/romhut.com#8]
Just reporting the download counter is not counting up and the upload date reset,  https://romhut.com/versions/danvdh-lightrom-06142015-zip was uploaded on June 14th, ROMhut says it was uploaded 2 days ago, this may confuse users in XDA threads.

**Comment by scottrobertson** [comment]
Download counter has been fixed, and download counts updated to the correct values.

Regarding the upload date, just to clarity, do you want the ability to set a release date?

**Comment by vashin1** [comment]
setting date would be a good solution, will fix the issue for me anyway

thanks a ton Scott,  DL count back to normal

**Comment by scottrobertson** [comment]
I think as a first step, I will set a "published_at" date when you click publish. Should be able to have the ability to set that manually at some point too.

**Comment by scottrobertson** [comment]
Sticking with what we have for now, which is that when you click publish, it sets the date to the current date.
